### ISSUE TITLE
Update error Kali Linux `sudo apt-get update && sudo apt-get full-upgrade -y && sudo apt-get dist-upgrade`

### ISSUE THREAD

**Issue by MiChaelinzo** [nu11secur1ty/Kali-Linux#2]
[](url)
<img width="441" alt="image" src="https://user-images.githubusercontent.com/68110223/155704146-5eb4c4d2-0de9-49f1-8d63-dc099cdaa1d6.png">

I have this error for months. I'm focusing in Cybersec and Penetration testing! I need this fix ASAP!

**Comment by MiChaelinzo** [comment]
<img width="407" alt="Screenshot 2022-02-25 140836" src="https://user-images.githubusercontent.com/68110223/155705319-ede765f2-c199-4831-b4bb-1f77f1903480.png">

**Comment by MiChaelinzo** [comment]
I `cat `and `rm `it but it's empty. I'm running in permission, how can someone unlock it?

**Comment by MiChaelinzo** [comment]
I fixed it but I got new issues from Ruby update/upgrade

**Comment by MiChaelinzo** [comment]
> I fixed it but I got new issues from Ruby update/upgrade

I just black screen and death my Kali Linux, don't follow what I do, but I have backup, thankfully. I still need to be careful next time downloading and using legacy software. I was updating my system in full-upgrade -y and dist-upgrade which deletes old repo/files that isn't congruent with the current system. 

Na black and death screen ko ang aking Kali Linux, huwag niyo basahin ang ginagawa ko, pero hindi ako nagaalala sahil meron naman along Backup sa Kali Linux system ko. Kailangan ko parin maging masisi pag nag download or gumamit mg legacy or lumang software. Ina update ko ang system da full- upgrade - y at dist-upgrade na aalisin ang lumang repo/files na hindi sumasangayon sa current na system.

**Comment by nu11secur1ty** [comment]
Hello dear friend, Everything is fixed =) thank you
Please let me know if something is not ok!?
BR

**Comment by MiChaelinzo** [comment]
> Hello dear friend, Everything is fixed =) thank you Please let me know if something is not ok!? BR

Nu11 yes it is, thank you! 
Also thanks for the replies in the Kali Linux Bounty.
I still having problems with external wifi adapters like Tp-Link AC1300 High Gain Wireless Mu-Mimo USB Adapter.
I also can't `make` or install drivers. It is working before updates...

**Comment by nu11secur1ty** [comment]
Yes, it is normal, every device with a little old date of creation is like that. No one wants to write current software drivers without money ;) 
So. I'm sorry for that, dear friend.

**Comment by MiChaelinzo** [comment]
> Yes, it is normal, every device with a little old date of creation is like that. No one wants to write current software drivers without money ;) So. I'm sorry for that, dear friend.

Do you accept paypal?
